baseURL = "http://www.alessiascudiero.info/"
languageCode = "en-us"
title = "Alessia Scudiero"
theme = "mysite-hugo-theme"
[params]
description = ""
keywords = ""
author = "Alessia Scudiero"
og_image = ""
